icon_add = I(_class='fa fa-plus fa-fw')
icon_check = I(_class='fa fa-check')
icon_warning = I(_class='fa fa-exclamation')
icon_sad_big = I(_class='fa fa-frown-o fa-5x fa-spin')
icon_loading = I(_class='fa fa-circle-o-notch fa-5x fa-spin')
icon_rocket_big = I(_class='fa fa-rocket fa-5x')
icon_graph_big = I(_class='fa fa-bar-chart fa-5x')
