string_add_long = "Hey! Looks like you haven't added any devices to your account, do that first."
string_manage = "Manage Procedures"
string_delete = "Delete Device"
string_add_short = "Add a Device"
string_undefined = "Undefined"
string_device_id = "Device ID: "
string_no_status = "Nothing to report status on"
string_no_device = "Add a device to get started!"
string_edit = "Edit Device"
string_get_started = "Select a device on the left to get started!"
string_no_data = " was just added, no data is ready yet."
string_start_edit = "Click here to start editing this script."
string_add_script = "Click here to add a new procedure for this device."
string_get_started_script = "Click any script on the left to get started."
string_desc = "Description: "
string_refresh = "Refresh to see data graph"

